# Generated by Django 4.2.20 on 2025-04-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_param', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
